require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/elevated_access_requests", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ElevatedAccessRequest. As you add validations to ElevatedAccessRequest, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ElevatedAccessRequest.create! valid_attributes
      get elevated_access_requests_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      elevated_access_request = ElevatedAccessRequest.create! valid_attributes
      get elevated_access_request_url(elevated_access_request)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_elevated_access_request_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      elevated_access_request = ElevatedAccessRequest.create! valid_attributes
      get edit_elevated_access_request_url(elevated_access_request)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ElevatedAccessRequest" do
        expect {
          post elevated_access_requests_url, params: { elevated_access_request: valid_attributes }
        }.to change(ElevatedAccessRequest, :count).by(1)
      end

      it "redirects to the created elevated_access_request" do
        post elevated_access_requests_url, params: { elevated_access_request: valid_attributes }
        expect(response).to redirect_to(elevated_access_request_url(ElevatedAccessRequest.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ElevatedAccessRequest" do
        expect {
          post elevated_access_requests_url, params: { elevated_access_request: invalid_attributes }
        }.to change(ElevatedAccessRequest, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post elevated_access_requests_url, params: { elevated_access_request: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested elevated_access_request" do
        elevated_access_request = ElevatedAccessRequest.create! valid_attributes
        patch elevated_access_request_url(elevated_access_request), params: { elevated_access_request: new_attributes }
        elevated_access_request.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the elevated_access_request" do
        elevated_access_request = ElevatedAccessRequest.create! valid_attributes
        patch elevated_access_request_url(elevated_access_request), params: { elevated_access_request: new_attributes }
        elevated_access_request.reload
        expect(response).to redirect_to(elevated_access_request_url(elevated_access_request))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        elevated_access_request = ElevatedAccessRequest.create! valid_attributes
        patch elevated_access_request_url(elevated_access_request), params: { elevated_access_request: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested elevated_access_request" do
      elevated_access_request = ElevatedAccessRequest.create! valid_attributes
      expect {
        delete elevated_access_request_url(elevated_access_request)
      }.to change(ElevatedAccessRequest, :count).by(-1)
    end

    it "redirects to the elevated_access_requests list" do
      elevated_access_request = ElevatedAccessRequest.create! valid_attributes
      delete elevated_access_request_url(elevated_access_request)
      expect(response).to redirect_to(elevated_access_requests_url)
    end
  end
end
